### ISSUE TITLE
What's up with firebase.gd? 

### ISSUE THREAD

**Issue by Oelda** [NeoSpark314/VoxelWorksQuest#11]
I was looking through the code, and noticed firebase looks to have some sketchy stuff, maybe I'm just overly cautious. I'm not a programmer or anything, I barely know anything about code, but I can't help but feel that `firebase.gd` is pretty off putting. so I was just wondering what `firebase.gd` does, and why is it there? is it creating a key for multiplayer? if so, why does it have email, password, url, google, token, HTTPRequest, and api in the code? Is it making a server from a website where you need an account from? either way, I haven't seen this in other games with multiplayer so this is very confusing for me, so I was hoping someone could explain to me! thanks in advance!

**Comment by NeoSpark314** [comment]
This code is used to access the firebase database via the firebase web API (https://firebase.google.com/docs/reference); The database is used to save the game worlds that a user wants to share with other users.

**Comment by Oelda** [comment]
I see, thank you, is it possible to be able to remove such code and run the game without errors or issues? as I wouldn't have anyone to share the world with, nor have a need to. thanks again for responding!

**Comment by NeoSpark314** [comment]
Should be very easy to remove as it is only used when the user decides to login and share his world. No other functionality depends on it.

**Comment by Oelda** [comment]
okay! thank you so much for your help, I hope you have a wonderful day :)
